const $=s=>document.querySelector(s); let all=[], map, layer;
const nf=n=>new Intl.NumberFormat('ko-KR').format(n||0);
const text=v=>v??'미확인';
function options(id,key){const el=$(id); [...new Set(all.map(d=>d[key]).filter(Boolean))].sort().forEach(v=>el.insertAdjacentHTML('beforeend',`<option>${v}</option>`))}
function filtered(){const q=$('#keyword').value.trim().toLowerCase();return all.filter(d=>(!q||`${d.facility_name} ${d.road_address}`.toLowerCase().includes(q))&&(!$('#facilityType').value||d.facility_type===$('#facilityType').value)&&(!$('#sido').value||d.sido===$('#sido').value)&&(!$('#location').value||d.location_type===$('#location').value)&&(!$('#building').value||d.building_type===$('#building').value)&&(!$('#response').value||d.response_type===$('#response').value))}
function count(data,key){return Object.entries(data.reduce((a,d)=>(a[text(d[key])]=(a[text(d[key])]||0)+1,a),{})).sort((a,b)=>b[1]-a[1])}
function bars(id,items){const max=Math.max(...items.map(x=>x[1]),1); $(id).innerHTML=items.map(([k,v])=>`<div class="bar-row"><div><span>${k}</span><div class="track"><div class="fill" style="width:${v/max*100}%"></div></div></div><b>${nf(v)}</b></div>`).join('')}
function render(){const data=filtered();const hospitals=data.filter(d=>d.facility_type==='요양병원').length, homes=data.length-hospitals, forest=data.filter(d=>d.forest_type==='산림인접형').length, poor=data.filter(d=>d.response_type==='119접근취약형').length;
 $('#kpis').innerHTML=[["조회 시설",data.length],["요양병원",hospitals],["요양원",homes],["산림인접형",forest],["119 접근취약형",poor]].map(([k,v])=>`<div class="kpi"><span>${k}</span><strong>${nf(v)}</strong></div>`).join('');
 bars('#typeChart',count(data,'facility_type'));bars('#profileChart',count(data,'building_type').slice(0,6));bars('#responseChart',count(data,'response_type'));
 $('#mapCount').textContent=`좌표 보유 ${nf(data.filter(d=>d.latitude&&d.longitude).length)}개`;layer.clearLayers();data.filter(d=>d.latitude&&d.longitude).forEach(d=>{const color=d.response_type==='119접근취약형'?'#e87432':'#0d6eae';L.circleMarker([d.latitude,d.longitude],{radius:4,color,fillOpacity:.72,weight:1}).bindPopup(`<b>${d.facility_name}</b><br>${d.facility_type}<br>${d.road_address}<br>건물: ${text(d.building_type)}<br>119 예상 접근: ${d.final_fire_response_min??'미확인'}분`).addTo(layer)});
 $('#tableCount').textContent=`${nf(data.length)}개 중 최대 300개 표시`;$('#rows').innerHTML=data.slice(0,300).map(d=>`<tr><td><b>${d.facility_name}</b></td><td><span class="tag">${d.facility_type}</span></td><td>${d.road_address}</td><td>${text(d.location_type)} · ${text(d.forest_type)}</td><td>${text(d.building_type)}</td><td>${text(d.size_type)}${d.occupants!=null?` (${nf(d.occupants)}명)`:''}</td><td>${text(d.response_type)}${d.final_fire_response_min!=null?` (${d.final_fire_response_min}분)`:''}</td></tr>`).join('');
}
fetch('data/facility_data.json').then(r=>r.json()).then(({metadata,records})=>{all=records;$('#asof').textContent=`기준일 ${metadata.as_of} · ${nf(metadata.facility_count)}개 시설`;map=L.map('map',{preferCanvas:true}).setView([36.3,127.8],7);L.tileLayer('https://{s}.tile.openstreetmap.org/{z}/{x}/{y}.png',{attribution:'© OpenStreetMap'}).addTo(map);layer=L.layerGroup().addTo(map);options('#facilityType','facility_type');options('#sido','sido');options('#location','location_type');options('#building','building_type');options('#response','response_type');document.querySelectorAll('.filters input,.filters select').forEach(e=>e.addEventListener('input',render));$('#reset').onclick=()=>{document.querySelectorAll('.filters input,.filters select').forEach(e=>e.value='');render()};render()}).catch(()=>{$('#asof').textContent='데이터 파일을 불러오지 못했습니다. build_data.py를 실행해 data/facility_data.json을 생성하세요.'});
